version: '3.7'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: victorrocha
      ME_CONFIG_BASICAUTH_PASSWORD: rotciv960503
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 030596victor
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 030596victor
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network
  app:
    restart: always
    build: app
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=030596victor
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_DB=players
  
    ports:
      - "3000:3000"
    links:
      - mongo
    networks:
      - mongo-compose-network
    depends_on:
      - mongo
networks: 
    mongo-compose-network:
      driver: bridge