version: '3.7'

services:
  neo4j:
    image: neo4j:4.1-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./plugins:/plugins
      - ./data:/data
      - ./import:/import
      - ./conf:/conf

    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=none
      - NEO4J_dbms_allow__upgrade=true
    
    restart: always
    
    networks:
      - neo4j_network

  app:
    restart: on-failure

    container_name: sistema_recomendacao
    
    build: app
    
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - neo4j
    depends_on:
      - neo4j

    networks:
      - neo4j_network
      - frontend_network

  kuber-movies:
    build: kuber-movies

    ports: 
      - "3000:3000"

    networks:
      - frontend_network

    depends_on: 
      - app

networks:
  neo4j_network:
    driver: bridge

  frontend_network: