version: '3'
services:
  app:
    restart: always
    container_name: sistema_recomendacao
    build: app
    ports:
      - "3040:3040"
    links:
      - neo4j
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:4.2.1
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - neo4j-network
    # depends_on:
    #   - kafka
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/data:/data
    environment:
      NEO4J_AUTH: neo4j/streams
      NEO4J_dbms_logs_debug_level: DEBUG
      NEO4J_dbms_connector.bolt.tls_level: OPTIONAL
      NEO4J_dbms_ssl.policy.bolt.client_auth: NONE
      NEO4J_dbms_ssl.policy.https.client_auth: NONE
  #     # KAFKA related configuration
  #     NEO4J_kafka_bootstrap_servers: kafka:19092
  #     NEO4J_streams_source_topic_nodes_neo4j: Person{*}
  #     NEO4J_streams_source_topic_relationships_neo4j: KNOWS{*}
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   hostname: zookeeper
  #   container_name: zookeeper
  #   ports:
  #     - "12181:12181"
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 12181

#   kafka:
#     image: confluentinc/cp-kafka:latest
#     hostname: kafka
#     container_name: kafka
#     ports:
#       - "19092:19092"
#     depends_on:
#       - zookeeper
#     environment:
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:12181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092

networks: 
  neo4j-network:
    driver: bridge
